### ISSUE TITLE
Recognize folders

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/Boost2Git#11]
Currently the output shows:

Revision 7623
++ WARNING: File '/branches/unlabeled-1.1.1.1.10/boost/boost/detail' not accounted for. Putting to fallback.
++ WARNING: File '/branches/unlabeled-1.1.1.1.10/boost/libs' not accounted for. Putting to fallback.

These two changes are actually **folders**. If a folder is not accounted for, Boost2Svn autumatically recurses. For some reason they are not recognized as folders.

**Comment by purpleKarrot** [comment]
Found out that `svn_fs_is_dir()` returns `false` for these paths. But `svn_fs_is_file()` returns `false` too!
I tested the early history and found out that **all** tested paths are neither files nor folders. I assume this is the case for all commits that originate in CVS.

**Comment by dabrahams** [comment]
Are you certain fs_root is set properly for the revision you wan to check?

Suppose you use `svn_fs_is_file()` and simply assume all non-files are directories?  Will that work?

**Comment by purpleKarrot** [comment]
I tried to list all directories that should recursed in a file. That caused "WARNING: Trying to recurse using a nonexistant path '/branches/unlabeled-1.1.1.1.10/boost/boost/detail'; ignoring" (http://jenkins.boost.org/job/Boost2Git/480/consoleFull).

`svn_fs_check_path()` reports `svn_node_none`.

**Comment by dabrahams** [comment]
Is this bug fixed now?

**Comment by purpleKarrot** [comment]
No, it is not fixed yet. Guessing currently does not catch all directories.

**Comment by dabrahams** [comment]
Investigating…

http://ci.boost.org/svn-trac/changeset/7623/ shows that in one revision, we have a directory copy from branches/unlabeled-1.1.1 to branches/unlabeled-1.1.1.1.10 followed by a bunch of deletions, **including branches/unlabeled-1.1.1.1.10/boost/boost/detail**.  Therefore, it never existed (there is no revision in which that path is a file or a directory)!  It should be no surprise that you get false for both. 

The path shows up in the log, apparently due to auto-recursion:

```
-- /branches/unlabeled-1.1.1.1.10 was copied from /branches/unlabeled-1.1.1 rev 7620
-- /branches/unlabeled-1.1.1.1.10/ is a copy-with-history, auto-recursing
-- /branches/unlabeled-1.1.1.1.10/boost/ rev 7623 did not match any rules; auto-recursing
-- /branches/unlabeled-1.1.1.1.10/boost/boost/ rev 7623 did not match any rules; auto-recursing
…
++ WARNING: File '/branches/unlabeled-1.1.1.1.10/boost/boost/detail' not accounted for. Putting to fallback.
```

As far as I can tell, this simply indicates an error somewhere in the svn2git logic, not a problem with svn.

**Comment by purpleKarrot** [comment]
What about this: if `svn_fs_check_path()` reports `svn_node_none` the change may be silently ignored?

**Comment by dabrahams** [comment]
Try it!

**Comment by purpleKarrot** [comment]
Fixed by 8fb2e2a4d4bf1175356dcc880baad20d1bb7d4e9.
